"""Renames checksum and status columns on images.

Revision ID: d4052e0e2fc1
Revises: e17aee692087
Create Date: 2024-07-17 19:11:41.819200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4052e0e2fc1"
down_revision: Union[str, None] = "e17aee692087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("_checksum", sa.Unicode(length=64), nullable=True)
    )
    op.add_column(
        "images",
        sa.Column(
            "_status",
            sa.Enum("IN_PROGRESS", "DONE", "CORRUPTED", name="imagestatus"),
            nullable=False,
        ),
    )
    op.drop_column("images", "checksum")
    op.drop_column("images", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column(
            "status",
            postgresql.ENUM("IN_PROGRESS", "DONE", "CORRUPTED", name="imagestatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "images",
        sa.Column(
            "checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("images", "_status")
    op.drop_column("images", "_checksum")
    # ### end Alembic commands ###
